### ISSUE TITLE
Text is not show 

### ISSUE THREAD

**Issue by imransiddiquiandroid** [blancham/react-native-wlkt#7]
import React, {Component} from 'react';
import {Text, View, Button} from 'react-native';
// import Intro, {IntroManage} from 'react-native-intro';
import {WalkthroughComponent, startWalkthrough} from 'react-native-wlkt';
const myAmazingScenario = [
  {
    component: 'textRnwlkt',
    tooltipOptions: {
      content: 'I am a TEXT element',
      text: {skip: ''},
      height: 150,
      width: 250,
      placement: 'leftop',
    },
  },
  {
    component: 'buttonRnwlkt',
    tooltipOptions: {
      content: 'I am a BUTTON element',
      text: {skip: ''},
      height: 150,
      width: 250,
    },
  },
];
export default class Home extends Component {
  render() {
    return (
      <>
        <WalkthroughComponent id="textRnwlkt">
          <Text>RNWLKT</Text>
        </WalkthroughComponent>
        <WalkthroughComponent id="buttonRnwlkt">
          <View>
            <Button
              title="RNWLKT"
              style={{width:100,height:25,marginTop:10}}
              onPress={() => {
                console.log('Clicked');
              }}
            />
          </View>
        </WalkthroughComponent>
        <Button
          title="Start"
          onPress={() => {
            startWalkthrough({scenario: myAmazingScenario});
          }}
        />
      </>
    );
  }
}

**Comment by imransiddiquiandroid** [comment]
![Screenshot_1617978226](https://user-images.githubusercontent.com/78909064/114194655-5adf4a00-996d-11eb-90dd-3c665ea07021.png)
![Screenshot_1617978240](https://user-images.githubusercontent.com/78909064/114194746-692d6600-996d-11eb-96ae-cbc38f0a4bba.png)

**Comment by blancham** [comment]
Hello @imransiddiquiandroid 

I ran the example on my machine and everything is working fine for **iOS** and **Android**.

I don't understand well your code without the formatting but what I can tell you about the screenshot you provided is that we don't see the top of the tooltip bubble.

Maybe you messed up the setup for the library and your text (+tooltip) is displayed underneath the buttons ?


If that's not the case please provide a code snippet that I can test on my machine 😉
